os:
 - linux
 - osx
matrix:
 allow_failures:
  - os: osx
before_install:
 - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./.travis/before_install/osx.sh; fi
 - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ./.travis/before_install/linux.sh; fi
install:
 - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./.travis/install/osx.sh; fi
 - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ./.travis/install/linux.sh; fi
script:
 - cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
 - make
 - sudo make install
notifications:
 email:
  recipients:
   - piotr.luczko@gmail.com
   - dmarkowicz@alari.pl
  on_success: change
  on_failure: always
