before_install:
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
install:
 - sudo apt-get install cmake make pkg-config g++ libssl-dev
 - sudo apt-get install qtbase5-dev qt5-default qt5-qmake
script:
 - chmod +x ./add-scc-to-whitelist.sh ./compile.sh
 - ./add-scc-to-whitelist.sh
 - ./compile.sh
after_success:
 - scc --version
