before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
install:
 - sudo apt-get install cmake make pkg-config g++ libssl-dev
 - sudo apt-get install qtbase5-dev qt5-default qt5-qmake
 - sudo apt-get install libqt5gui5-dev libqt5dbus5-dev libqt5core5-dev libqt5xml5-dev libqt5webkitwidgets5-dev libqt5webkit5-dev libqt5network5-dev libqt5multimedia5-dev libqt5widgets5-dev libqt5sql5-dev libqt5qml5-dev libqt5quick5-dev libqt5sensors5-dev libqt5positioning5-dev libqt5opengl5-dev libqt5printsupport5-dev libqt5multimediawidgets5-dev libqt5webchannel5 libqt5svg5-dev
 - sudo apt-get install libqca-qt5-2-dev
script:
 - ./add-scc-to-whitelist.sh
 - ./compile.sh
after_success:
 - scc --version
